<?php
declare(strict_types=1);

require __DIR__ . '/../src/Response.php';
require __DIR__ . '/../src/helpers.php';
$config = require __DIR__ . '/../config/config.php';
$method = $_SERVER['REQUEST_METHOD'];
$path = rtrim(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) ?: '/', '/') ?: '/';

header('Access-Control-Allow-Origin: ' . $config['cors_origin']);
header('Access-Control-Allow-Headers: Content-Type, Authorization');
header('Access-Control-Allow-Methods: GET, POST, PATCH, DELETE, OPTIONS');
if ($method === 'OPTIONS') { http_response_code(204); exit; }
if ($method === 'GET' && $path === '/api/health') { Response::json(['ok'=>true,'driver'=>'mysql','time'=>now_sql()]); exit; }

require __DIR__ . '/../src/Database.php';
require __DIR__ . '/../src/Transformers.php';
try { $db = new Database($config['database']); }
catch (Throwable $e) { Response::error('No se pudo conectar a MySQL', 500, ['detail'=>$config['debug'] ? $e->getMessage() : null]); exit; }

try { route($method, $path, $db); }
catch (Throwable $e) { Response::error('Error interno del servidor', 500, ['detail'=>$config['debug'] ? $e->getMessage() : null]); }

function route(string $method, string $path, Database $db): void {
    if ($method === 'GET' && $path === '/api/db-health') { $db->one('SELECT 1 ok'); Response::json(['ok'=>true,'database'=>'connected']); return; }
    if ($method === 'GET' && $path === '/api/dashboard') { dashboard($db); return; }
    if ($method === 'GET' && $path === '/api/events') { $rows=$db->all(event_sql().' ORDER BY e.starts_on DESC'); Response::json(array_map(fn($r)=>event_row($r, sessions($db,$r['id'])), $rows)); return; }
    if ($method === 'POST' && $path === '/api/events') { create_event($db); return; }
    if (preg_match('#^/api/events/([^/]+)$#',$path,$m) && $method==='GET') { $ev=event_by_id($db,$m[1]); $ev ? Response::json($ev) : Response::error('Evento no encontrado',404); return; }
    if (preg_match('#^/api/events/([^/]+)$#',$path,$m) && $method==='PATCH') { update_event($db,$m[1]); return; }
    if (preg_match('#^/api/events/([^/]+)/guests$#',$path,$m)) { if ($method==='GET') guests($db,$m[1]); elseif ($method==='POST') create_guest($db,$m[1],false); return; }
    if (preg_match('#^/api/events/([^/]+)/walk-ins$#',$path,$m) && $method==='POST') { create_guest($db,$m[1],true); return; }
    if ($method==='GET' && $path==='/api/guests') { guests($db,null); return; }
    if (preg_match('#^/api/guests/([^/]+)/confirmation$#',$path,$m) && $method==='PATCH') { $c=str_input(request_json(),'confirmacion'); if(!in_array($c,['aceptado','tentativo','rechazado','pendiente'],true)){Response::error('Confirmacion invalida',422);return;} $db->execute('UPDATE guests SET confirmation=? WHERE id=?',[$c,$m[1]]); Response::json(['updated'=>true]); return; }
    if (preg_match('#^/api/guests/([^/]+)/(check-in|check-out)$#',$path,$m) && $method==='POST') { check_guest($db,$m[1],$m[2]==='check-in'); return; }
    if (preg_match('#^/api/guests/([^/]+)$#',$path,$m) && $method==='DELETE') { $db->execute('DELETE FROM guests WHERE id=?',[$m[1]]); Response::json(['deleted'=>true]); return; }
    if ($method==='GET' && $path==='/api/visitors') { visitors($db); return; }
    if ($method==='POST' && $path==='/api/visitors') { create_visit($db); return; }
    if ($method==='GET' && $path==='/api/visitors/search') { search_visitors($db); return; }
    if (preg_match('#^/api/visitors/([^/]+)/exit$#',$path,$m) && $method==='POST') { $db->execute('UPDATE visits SET exit_at=? WHERE id=?',[now_sql(),$m[1]]); Response::json(['updated'=>true]); return; }
    if ($method==='GET' && $path==='/api/settings') { Response::json(settings($db)); return; }
    if ($method==='PATCH' && $path==='/api/settings') { foreach(request_json() as $k=>$v) $db->execute('INSERT INTO settings (setting_key,setting_value) VALUES (?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)',[(string)$k,is_scalar($v)?(string)$v:json_encode($v)]); Response::json(settings($db)); return; }
    if ($method==='GET' && $path==='/api/users') { Response::json($db->all('SELECT id,name AS nombre,role AS rol,email AS correo FROM users ORDER BY name')); return; }
    if ($method==='GET' && $path==='/api/guest-types') { Response::json($db->all('SELECT id,name AS nombre,color FROM guest_types ORDER BY sort_order,name')); return; }
    if ($method==='POST' && $path==='/api/guest-types') { $name=str_input(request_json(),'nombre'); if(!$name){Response::error('El nombre del tipo es obligatorio',422);return;} $id=new_id('gt_'); $db->execute('INSERT INTO guest_types (id,name,color,sort_order) VALUES (?,?,?,?)',[$id,$name,'#1d4ed8',100]); Response::json($db->one('SELECT id,name AS nombre,color FROM guest_types WHERE id=?',[$id]),201); return; }
    if (preg_match('#^/api/reports/([^/]+)$#',$path,$m) && $method==='GET') { report($db,$m[1]); return; }
    Response::error('Ruta no encontrada',404);
}
function event_sql(): string { return "SELECT e.*,(SELECT COUNT(*) FROM guests g WHERE g.event_id=e.id) guest_count,(SELECT COUNT(*) FROM guests g WHERE g.event_id=e.id AND g.confirmation='aceptado') confirmed_count,(SELECT COUNT(*) FROM guests g WHERE g.event_id=e.id AND g.arrival_at IS NOT NULL) present_count FROM events e"; }
function sessions(Database $db,string $eventId): array { return $db->all('SELECT * FROM event_sessions WHERE event_id=? ORDER BY session_date,starts_at',[$eventId]); }
function event_by_id(Database $db,string $id): ?array { $r=$db->one(event_sql().' WHERE e.id=?',[$id]); return $r?event_row($r,sessions($db,$id)):null; }
function create_event(Database $db): void { $d=request_json(); $name=str_input($d,'nombre'); if(!$name){Response::error('El nombre del evento es obligatorio',422);return;} $id=new_id('ev_'); $date=str_input($d,'fecha',date('Y-m-d')); $db->pdo()->beginTransaction(); $db->execute('INSERT INTO events (id,name,description,starts_on,ends_on,location,status,requires_confirmation) VALUES (?,?,?,?,?,?,?,?)',[$id,$name,str_input($d,'descripcion',''),$date,str_input($d,'fechaFin',$date),str_input($d,'lugar','Sin ubicacion'),str_input($d,'estado','borrador'),bool_input($d,'requiereConfirmacion',true)?1:0]); $db->execute('INSERT INTO event_sessions (id,event_id,name,session_date,starts_at,ends_at) VALUES (?,?,?,?,?,?)',[new_id('ses_'),$id,'Horario principal',$date,str_input($d,'inicio','09:00'),str_input($d,'fin','17:00')]); $db->pdo()->commit(); Response::json(event_by_id($db,$id),201); }
function update_event(Database $db,string $id): void { $d=request_json(); $sets=[]; $p=[]; $map=['nombre'=>'name','descripcion'=>'description','fechaInicio'=>'starts_on','fechaFin'=>'ends_on','lugar'=>'location','estado'=>'status']; foreach($map as $input=>$column){ if(array_key_exists($input,$d)){ if($input==='estado'&&!in_array((string)$d[$input],['borrador','activo','finalizado'],true)){Response::error('Estado invalido',422);return;} $sets[]="$column=?"; $p[]=is_scalar($d[$input])?(string)$d[$input]:null; } } if(array_key_exists('requiereConfirmacion',$d)){ $sets[]='requires_confirmation=?'; $p[]=bool_input($d,'requiereConfirmacion',false)?1:0; } if(!$sets){ $ev=event_by_id($db,$id); $ev?Response::json($ev):Response::error('Evento no encontrado',404); return; } $p[]=$id; $db->execute('UPDATE events SET '.implode(',',$sets).' WHERE id=?',$p); $ev=event_by_id($db,$id); $ev?Response::json($ev):Response::error('Evento no encontrado',404); }
function guest_select(): string { return 'SELECT g.*,gt.name AS type_name FROM guests g JOIN guest_types gt ON gt.id=g.guest_type_id'; }
function guests(Database $db,?string $eventId): void { $sql=guest_select(); $p=[]; if($eventId){$sql.=' WHERE g.event_id=?';$p[]=$eventId;} Response::json(array_map('guest_row',$db->all($sql.' ORDER BY g.name',$p))); }
function guest_type_id(Database $db,string $name): string { $r=$db->one('SELECT id FROM guest_types WHERE name=?',[$name]); if($r)return $r['id']; $id=new_id('gt_'); $db->execute('INSERT INTO guest_types (id,name,color,sort_order) VALUES (?,?,?,?)',[$id,$name,'#1d4ed8',100]); return $id; }
function create_guest(Database $db,string $eventId,bool $walkIn): void { $d=request_json(); $name=str_input($d,'nombre'); if(!$name){Response::error('El nombre es obligatorio',422);return;} $id=new_id($walkIn?'walk_':'g_'); $type=$walkIn?str_input($d,'tipo','Protocolo'):str_input($d,'tipo','Estandar'); $db->execute('INSERT INTO guests (id,event_id,guest_type_id,name,document_id,position,institution,email,confirmation,arrival_at,is_walk_in) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[$id,$eventId,guest_type_id($db,$type),$name,str_input($d,'cedula','Sin documento'),str_input($d,'cargo',''),str_input($d,'institucion',''),str_input($d,'correo',''),str_input($d,'confirmacion',$walkIn?'aceptado':'pendiente'),$walkIn?now_sql():str_input($d,'llegada'),$walkIn?1:0]); Response::json(guest_row($db->one(guest_select().' WHERE g.id=?',[$id])),201); }
function check_guest(Database $db,string $guestId,bool $in): void { $d=request_json(); $time=now_sql(); $db->execute('UPDATE guests SET '.($in?'arrival_at':'departure_at').'=? WHERE id=?',[$time,$guestId]); $db->execute('INSERT INTO attendance_logs (id,guest_id,event_session_id,action,happened_at) VALUES (?,?,?,?,?)',[new_id('att_'),$guestId,str_input($d,'sesionId'),$in?'entrada':'salida',$time]); Response::json(['updated'=>true,$in?'llegada':'salida'=>$time]); }
function visitor_select(): string { return 'SELECT v.*,vs.id visit_id,vs.area,vs.reason,vs.entry_at,vs.exit_at,(SELECT COUNT(*) FROM companions c WHERE c.visit_id=vs.id) companions_count FROM visits vs JOIN visitors v ON v.id=vs.visitor_id'; }
function visitors(Database $db): void { $s=$_GET['status']??'todos'; $where=$s==='dentro'?' WHERE vs.exit_at IS NULL':($s==='fuera'?' WHERE vs.exit_at IS NOT NULL':''); Response::json(array_map('visitor_row',$db->all(visitor_select().$where.' ORDER BY vs.entry_at DESC'))); }
function search_visitors(Database $db): void { $q='%'.trim((string)($_GET['q']??'')).'%'; Response::json($db->all('SELECT id AS visit_id,id,document_id AS cedula,document_id,name AS nombre,name,position AS cargo,position,institution AS institucion,institution,phone AS telefono,phone,email AS correo,email,photo_url AS foto,photo_url,"" AS area,"" AS reason,"" AS entry_at,NULL AS exit_at,0 AS companions_count FROM visitors WHERE document_id LIKE ? OR name LIKE ? OR institution LIKE ? ORDER BY name LIMIT 10',[$q,$q,$q])); }
function create_visit(Database $db): void { $d=request_json(); $name=str_input($d,'nombre'); $doc=str_input($d,'cedula'); if(!$name||!$doc){Response::error('Cedula y nombre son obligatorios',422);return;} $db->pdo()->beginTransaction(); $ex=$db->one('SELECT id FROM visitors WHERE document_id=?',[$doc]); $visitorId=$ex['id']??new_id('v_'); if($ex)$db->execute('UPDATE visitors SET name=?,position=?,institution=?,phone=?,email=? WHERE id=?',[$name,str_input($d,'cargo',''),str_input($d,'institucion',''),str_input($d,'telefono',''),str_input($d,'correo',''),$visitorId]); else $db->execute('INSERT INTO visitors (id,document_id,name,position,institution,phone,email,photo_url) VALUES (?,?,?,?,?,?,?,?)',[$visitorId,$doc,$name,str_input($d,'cargo',''),str_input($d,'institucion',''),str_input($d,'telefono',''),str_input($d,'correo',''),str_input($d,'foto')]); $visitId=new_id('vis_'); $db->execute('INSERT INTO visits (id,visitor_id,area,reason,entry_at) VALUES (?,?,?,?,?)',[$visitId,$visitorId,str_input($d,'area',''),str_input($d,'motivo',''),now_sql()]); foreach(($d['acompanantes']??[]) as $c) if(is_array($c)&&trim((string)($c['nombre']??''))!=='') $db->execute('INSERT INTO companions (id,visit_id,name,document_id) VALUES (?,?,?,?)',[new_id('cmp_'),$visitId,trim((string)$c['nombre']),trim((string)($c['cedula']??''))]); $db->pdo()->commit(); Response::json(visitor_row($db->one(visitor_select().' WHERE vs.id=?',[$visitId])),201); }
function dashboard(Database $db): void { $today=date('Y-m-d'); Response::json(['visitantesHoy'=>(int)$db->one('SELECT COUNT(*) c FROM visits WHERE DATE(entry_at)=?',[$today])['c'],'eventosActivos'=>(int)$db->one("SELECT COUNT(*) c FROM events WHERE status='activo'")['c'],'invitadosConfirmados'=>(int)$db->one("SELECT COUNT(*) c FROM guests WHERE confirmation='aceptado'")['c'],'presentesHoy'=>(int)$db->one('SELECT COUNT(*) c FROM guests WHERE DATE(arrival_at)=?',[$today])['c'],'visitantesDentro'=>(int)$db->one('SELECT COUNT(*) c FROM visits WHERE exit_at IS NULL')['c'],'proximosEventos'=>(int)$db->one("SELECT COUNT(*) c FROM events WHERE status<>'finalizado'")['c']]); }
function settings(Database $db): array { $out=[]; foreach($db->all('SELECT setting_key,setting_value FROM settings') as $r)$out[$r['setting_key']]=$r['setting_value']; return $out; }
function report(Database $db,string $type): void { if($type==='visitantes'||$type==='fotografico'){Response::json(['tipo'=>$type,'items'=>array_map('visitor_row',$db->all(visitor_select().' ORDER BY vs.entry_at DESC'))]);return;} if(in_array($type,['asistencia','confirmados','ausentes'],true)){ $eventId=$_GET['eventoId']??null; $sql=guest_select(); $p=[]; if($eventId){$sql.=' WHERE g.event_id=?';$p[]=$eventId;} $items=array_map('guest_row',$db->all($sql.' ORDER BY g.name',$p)); if($type==='confirmados')$items=array_values(array_filter($items,fn($i)=>$i['confirmacion']==='aceptado')); if($type==='ausentes')$items=array_values(array_filter($items,fn($i)=>$i['confirmacion']==='aceptado'&&!$i['llegada'])); Response::json(['tipo'=>$type,'items'=>$items]); return; } Response::error('Reporte no soportado',404); }
